#!/usr/bin/env python3
"""Render the Wind Compass app icon and visualization picker icon.

Two different images, both derived from the real compass skin palettes:

  * app icons    package/static/appIcon*.png, 36/72px square, shown in the
                 Splunk launcher and on Splunkbase.
  * picker icon  visualizations/windcompass/preview.png, 116x76, shown in
                 Dashboard Studio's visualization picker. Splunk requires this
                 exact name, size and format, and Splunkbase rejects a
                 visualization stanza that has no picker icon.

The three designs mirror the three visualization skins defined in
visualizations/windcompass/src/themes/skins.js, so the app icon looks like the
visualization it ships. "clean" is the installed design.

Tick layout is 4 cardinals + 4 intercardinals + fine marks, with the north tick
replaced by a marker triangle: an evenly spaced 12-mark dial reads as a clock
face rather than a compass.

Development tool only — not part of the shipped app. Requires Pillow
(`pip install Pillow`), which is deliberately not a project dependency since the
icons are regenerated by hand and committed.

Usage:
    python3 tools/render_app_icon.py                     # preview all three designs
    python3 tools/render_app_icon.py --install clean     # write both icon sets
"""

import argparse
import math
import os
from PIL import Image, ImageDraw

SS = 4                                  # supersample factor for antialiasing
BASE = 512                              # preview size
S = BASE * SS                           # working canvas
C = S / 2
NEEDLE_ANGLE = 38.0                     # degrees clockwise from north

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_DIR = os.path.join(REPO, 'package', 'static')
PREVIEW_DIR = os.path.join(REPO, 'dist', 'icon-proposals')
VIZ_PREVIEW_PATH = os.path.join(REPO, 'visualizations', 'windcompass', 'preview.png')

# Splunk app icon sizes: appIcon is 36px, appIcon_2x is 72px.
ICON_FILES = [('appIcon', 36), ('appIcon_2x', 72), ('appIconAlt', 36), ('appIconAlt_2x', 72)]

# Fixed by Splunk for the visualization picker: 116x76 PNG, landscape.
PICKER_W, PICKER_H = 116, 76

CARDINALS = [90, 180, 270]              # north omitted; it carries the marker triangle
INTERCARDINALS = [45, 135, 225, 315]
FINE = [a for a in range(0, 360, 22) if a % 45 != 0][:8]


def polar(angle_deg, radius):
    a = math.radians(angle_deg - 90)
    return (C + radius * math.cos(a), C + radius * math.sin(a))


def disc(draw, r, color):
    draw.ellipse([C - r, C - r, C + r, C + r], fill=color)


def outline_ring(draw, r, color, width):
    """Stroke a ring. Uses outline rather than punching a hole, which in RGBA
    would replace the pixels underneath instead of compositing over them."""
    half = width / 2
    draw.ellipse([C - r + half, C - r + half, C + r - half, C + r - half],
                 outline=color, width=max(1, int(width)))


def ticks(draw, angles, r_inner, r_outer, color, width):
    for ang in angles:
        draw.line([polar(ang, r_inner), polar(ang, r_outer)], fill=color, width=max(1, int(width)))


def needle(draw, angle, r_head, r_tail, half_width, head_color, tail_color):
    left, right = polar(angle - 90, half_width), polar(angle + 90, half_width)
    draw.polygon([polar(angle, r_head), right, left], fill=head_color)
    if r_tail > 0:
        lt, rt = polar(angle + 90, half_width * 0.75), polar(angle - 90, half_width * 0.75)
        draw.polygon([polar(angle + 180, r_tail), rt, lt], fill=tail_color)


def north_marker(draw, r, size, color):
    draw.polygon([polar(0, r), polar(-7, r - size), polar(7, r - size)], fill=color)


def new_canvas():
    img = Image.new('RGBA', (S, S), (0, 0, 0, 0))
    return img, ImageDraw.Draw(img)


def design_clean():
    """Skin "clean": minimal dark dial, light hairline bezel, red needle."""
    img, d = new_canvas()
    R = S * 0.47
    disc(d, R, (27, 31, 38, 255))
    outline_ring(d, R, (216, 221, 229, 240), S * 0.022)
    ticks(d, FINE, R * 0.86, R * 0.93, (255, 255, 255, 80), S * 0.010)
    ticks(d, INTERCARDINALS, R * 0.80, R * 0.93, (255, 255, 255, 120), S * 0.016)
    ticks(d, CARDINALS, R * 0.70, R * 0.93, (255, 255, 255, 190), S * 0.026)
    north_marker(d, R * 0.93, R * 0.16, (231, 76, 60, 255))
    needle(d, NEEDLE_ANGLE, R * 0.74, R * 0.46, S * 0.022, (231, 76, 60, 255), (192, 57, 43, 255))
    r = S * 0.026
    d.ellipse([C - r, C - r, C + r, C + r], fill=(236, 240, 241, 255))
    return img


def design_marine():
    """Skin "marine": navy bezel, deep navy dial, classic light-blue needle."""
    img, d = new_canvas()
    R = S * 0.48
    disc(d, R, (30, 58, 95, 255))
    outline_ring(d, R, (74, 118, 172, 255), S * 0.016)
    dial = R * 0.80
    disc(d, dial, (13, 26, 42, 255))
    outline_ring(d, dial, (58, 90, 122, 255), S * 0.010)
    ticks(d, FINE, dial * 0.84, dial * 0.95, (58, 90, 122, 255), S * 0.012)
    ticks(d, INTERCARDINALS, dial * 0.78, dial * 0.95, (90, 138, 184, 255), S * 0.018)
    ticks(d, CARDINALS, dial * 0.66, dial * 0.95, (120, 170, 215, 255), S * 0.034)
    north_marker(d, dial * 0.95, dial * 0.20, (168, 200, 232, 255))
    needle(d, NEEDLE_ANGLE, dial * 0.78, dial * 0.78, S * 0.040,
           (168, 200, 232, 255), (62, 92, 124, 255))
    r = S * 0.038
    d.ellipse([C - r, C - r, C + r, C + r], fill=(168, 200, 232, 255))
    r2 = S * 0.015
    d.ellipse([C - r2, C - r2, C + r2, C + r2], fill=(13, 26, 42, 255))
    return img


def design_instrument():
    """Skin "instrument": black HUD gauge, fine ticks, white needle, tail ring."""
    img, d = new_canvas()
    R = S * 0.48
    disc(d, R, (42, 42, 42, 255))
    dial = R * 0.87
    disc(d, dial, (17, 17, 17, 255))
    fine = [a for a in range(0, 360, 15) if a % 45 != 0]
    ticks(d, fine, dial * 0.88, dial * 0.97, (85, 85, 85, 255), S * 0.009)
    ticks(d, INTERCARDINALS, dial * 0.84, dial * 0.97, (130, 130, 130, 255), S * 0.014)
    ticks(d, CARDINALS, dial * 0.74, dial * 0.97, (180, 180, 180, 255), S * 0.026)
    north_marker(d, dial * 0.97, dial * 0.18, (255, 255, 255, 255))
    hub = dial * 0.30
    disc(d, hub, (36, 36, 36, 255))
    outline_ring(d, hub, (62, 62, 62, 255), S * 0.008)
    needle(d, NEEDLE_ANGLE, dial * 0.80, dial * 0.46, S * 0.018,
           (255, 255, 255, 255), (200, 200, 200, 255))
    tx, ty = polar(NEEDLE_ANGLE + 180, dial * 0.46)
    r = S * 0.034
    d.ellipse([tx - r, ty - r, tx + r, ty + r], outline=(255, 255, 255, 255), width=int(S * 0.011))
    return img


DESIGNS = {
    'clean': ('Clean skin', design_clean),
    'marine': ('Marine skin', design_marine),
    'instrument': ('Instrument skin', design_instrument),
}


def write_previews(outdir):
    os.makedirs(outdir, exist_ok=True)
    renders = []
    for slug, (label, fn) in DESIGNS.items():
        full = fn()
        for size in (BASE, 72, 36):
            full.resize((size, size), Image.LANCZOS).save(
                os.path.join(outdir, f'proposal-{slug}-{size}.png'))
        renders.append(full.resize((BASE, BASE), Image.LANCZOS))
        print(f'preview: {slug}')

    pad, cell, strip = 40, BASE, 140
    sheet_w = pad + (cell + pad) * len(renders)
    sheet = Image.new('RGBA', (sheet_w, pad + cell + pad + strip), (18, 20, 26, 255))
    sheet.paste(Image.new('RGBA', (sheet_w, strip), (255, 255, 255, 255)), (0, pad + cell + pad))
    for i, img in enumerate(renders):
        x = pad + i * (cell + pad)
        sheet.paste(img, (x, pad), img)
        for j, size in enumerate((72, 36)):
            small = img.resize((size, size), Image.LANCZOS)
            sheet.paste(small, (x + j * 110, pad + cell + pad + 30), small)
    sheet.save(os.path.join(outdir, 'proposals-contact-sheet.png'))
    print('preview: contact sheet')


def render_picker_icon(full, background):
    """Fit the square dial into Splunk's landscape 116x76 picker tile.

    The dial is sized so its bezel meets the top and bottom edges, and the
    remaining side margins are filled with the dial's own background colour —
    Splunk's design guidance asks for a tile with no transparent gaps or
    visible borders.
    """
    w, h = PICKER_W * SS, PICKER_H * SS
    tile = Image.new('RGBA', (w, h), background)
    dial_size = int(h * 1.02)
    dial = full.resize((dial_size, dial_size), Image.LANCZOS)
    tile.paste(dial, ((w - dial_size) // 2, (h - dial_size) // 2), dial)
    return tile.resize((PICKER_W, PICKER_H), Image.LANCZOS)


# Background for the picker tile, per design: the dial colour of each skin.
PICKER_BACKGROUNDS = {
    'clean': (27, 31, 38, 255),
    'marine': (13, 26, 42, 255),
    'instrument': (17, 17, 17, 255),
}


def install(slug):
    label, fn = DESIGNS[slug]
    full = fn()
    for name, size in ICON_FILES:
        path = os.path.join(STATIC_DIR, f'{name}.png')
        full.resize((size, size), Image.LANCZOS).save(path)
        print(f'installed {name}.png ({size}x{size}) from "{label}"')

    render_picker_icon(full, PICKER_BACKGROUNDS[slug]).save(VIZ_PREVIEW_PATH)
    print(f'installed preview.png ({PICKER_W}x{PICKER_H}) from "{label}"')


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--install', choices=sorted(DESIGNS), help='write icons into package/static')
    ap.add_argument('--preview-dir', default=PREVIEW_DIR)
    args = ap.parse_args()
    if args.install:
        install(args.install)
    else:
        write_previews(args.preview_dir)


if __name__ == '__main__':
    main()
